[package]
name = "iced-framebuffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colstodian = "0.1.0-rc.3"
iced = { version = "0.8.0", features = ["image"] }
